EASY/EASY/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('elements.urls', namespace='elements'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EASY/elements/urls.py
from django.urls import path
from . import views

app_name = 'elements'

urlpatterns = [
    path('', views.index0, name='index0'),
    path('<int:pk>', views.detail, name='detail'),
    path('index/', views.index, name='index'),
    path('contacto/', views.contacto, name='contacto'),
] 

EASY/elements/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)

    def __str__(self):
        return self.title
    

class Type(models.Model):
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)

    def __str__(self):
        return self.title

class Element(models.Model):
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, null=True, blank=True)
    
    description = models.TextField()
    content = models.TextField(null=True, blank=True)

    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)

    image = models.ImageField(upload_to='elements/', blank=True, null=True)

    def __str__(self):
        return self.title



class Carousel(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    image1 = models.ImageField(upload_to='carousel/')
    image2 = models.ImageField(upload_to='carousel/')
    image3 = models.ImageField(upload_to='carousel/')

    def __str__(self):
        return self.title

EASY/elements/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import Element, Category, Carousel

# Create your views here.

def index(request):
   ## elements = Element.objects.filter(type=2).all()

    search = request.GET.get('search') if request.GET.get('search') else '' 
    
    category_id = request.GET.get('category_id')
    category_id = int(category_id) if category_id else ''

    elements = Element.objects

    if search:
        elements = Element.objects.filter(title__contains=search)
    

    if category_id:
        elements = elements.filter(category_id=category_id)
    
    elements = elements.filter(type=2).all()

    categories = Category.objects.all()

    paginator = Paginator(elements,10)
    page_number = request.GET.get('page')
    return render(request, 'elements/index.html', {'elements':paginator.get_page(page_number), 'search':search, 'category_id':category_id, 'categories':categories})


def detail(request, pk):
    element = Element.objects.get(id=pk)
    return render(request, 'elements/detail.html',{'element':element})

def index0(request):
    carousels = Carousel.objects.all()
    search = request.GET.get('search') if request.GET.get('search') else '' 
    
    category_id = request.GET.get('category_id')
    category_id = int(category_id) if category_id else ''

    elements = Element.objects

    if search:
        elements = Element.objects.filter(title__contains=search)
    

    if category_id:
        elements = elements.filter(category_id=category_id)
    
    elements = elements.filter(type=2).all()

    categories = Category.objects.all()

    paginator = Paginator(elements,10)
    page_number = request.GET.get('page')
    return render(request, 'elements/index0.html', {'carousels': carousels,'elements':paginator.get_page(page_number), 'search':search, 'category_id':category_id, 'categories':categories})


def contacto(request):
    return render(request, 'elements/contacto.html')

EASY/elements/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Easy</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/cards.css' %}">
</head>
<body>
   <div class="container-fluid m-0 p-0">
    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'elements:index0' %}">EASY</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'elements:index0' %}">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'elements:index' %}">Productos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'elements:contacto' %}">Contacto</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
    {% block content %}
    {% endblock %}
   </div>

    {% block footer %} 
        <footer><p></p></footer>
    {% endblock %}
    
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

EASY/elements/templates/elements/contacto.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="" style="background-image: url('/static/fonts/contacto.jpg'); background-size: cover; background-position: center;">
        <div class="d-flex justify-content-center align-items-center" style="height: 100vh; ">
            <a class="btn btn-success" href="https://api.whatsapp.com/send/?phone=%2B543644369582&text&type=phone_number&app_absent=0"><h2>Contactame por whatsapp</h2></a>
        </div>
        
    </div>

{% endblock %}

EASY/elements/templates/elements/detail.html
{% extends 'base.html' %}

{% block content %}
    <!-- <div class="card">
        <div class="card-header">
            <h1>{{element.title}}</h1>
        </div>
        <div class="card-body">
            <div>{{element.description}}</div>
            <div>{{element.content}}</div>
        </div>
    </div> -->
    


    <!--  -->
   <!-- <div class="container mt-5">
     <div class="card mb-3" style="max-width: 400px;">
  <div class="row g-0">
    <div class="col-md-4 w-100">
      <img src="{{element.image.url}}" class="img-fluid rounded " alt="...">
    </div>
    <div class="container">
      <div class="card-body">
        <h5 class="card-title">{{element.title}}</h5>
        <p class="card-text">{{element.price}}</p>
        <p class="card-text"><small class="text-body-secondary">{{element.created}}</small></p>
        <a href="" class="btn btn-outline-success">Envíanos un mensaje</a>
      </div>
    </div>
  </div>
</div>

   </div> -->
<div class="container d-flex justify-content-center">
     <div class="card" style="width: 50rem;">
  <img src="{{element.image.url}}" class="card-img-top" alt="..." style="max-height: 40rem;">
  <div class="card-body">
    <h5 class="card-title">{{element.title}}</h5>
    <!-- <p class="card-text">{{element.content}}</p> -->
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">{{element.content}}</li>
    <li class="list-group-item">{{element.description}}</li>
    <li class="list-group-item">${{element.price}}</li>
  </ul>
  <div class="card-body">

      <a href="#" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Envianos un mensaje</a>
    
  </div>
</div>
</div>

    
    
{% endblock %}

EASY/elements/templates/elements/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Elementos{% endblock %}

{% block content %}
 
       <div class="container">
         <form method="get" class="row mb-5">
        <div class="col-auto">
            <input type="text" name="search" class="form-control" placeholder="Buscar" value={{search}}>
        </div>
        <div class="col-auto">
            <select name="category_id" class="form-select">
                <option value="">Categorias</option>
                {% for c in categories %}
                <option

                    {% if category_id == c.id %}
                    selected
                    {% endif %}

                    value={{c.id}}>
                    {{c.title}}
                </option>
            
                {% endfor %}
            </select>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-dark">Buscar</button>
        </div>
        <div class="col-auto">
            <a href="{% url 'elements:index' %}" class="btn btn-outline-secondary">Limpiar</a>
        </div>
    </form>
         
         <div class="card__container">
            {% for e in elements %}
            <article class="card__article p-5">
               <img src="{{e.image.url}}" alt="image" class="card__img img-fluid border rounded-3 shadow-lg" style="min-height: 15rem; max-height: 15rem; max-width: 19.5rem;">

               <div class="card__data">
                  <span class="card__description">{{e.content}}</span>
                  <h2 class="card__title">{{e.title}}</h2>
                  <a href="{% url 'elements:detail' e.id %}" class="card__button">Comprar ahora</a>
               </div>
            </article>
             {% endfor %}
         </div>
          
      </div>
    
{% include "partials\pagination.html" with page_obj=elements %}
{% endblock %}

EASY/elements/templates/elements/index0.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">

    {% for carousel in carousels %}
    {% if carousel.image1 %}
      <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <img src="{{ carousel.image1.url }}" class="d-block w-100" alt="slider" style="height:95vh; object-fit:cover;">
        <div class="carousel-caption top-0 mt-4 d-flex flex-column justify-content-center align-items-center">
          <a href="{% url 'elements:index' %}" class="btn btn-outline-dark">Ver más</a>
        </div>
      </div>
    {% endif %}
    {% if carousel.image2 %}
      <div class="carousel-item">
        <img src="{{ carousel.image2.url }}" class="d-block w-100" alt="slider" style="height:95vh; object-fit:cover;">
        <div class="carousel-caption top-0 mt-4 d-flex flex-column justify-content-center align-items-center">
          <p class="mt-5 fs-3 text-uppercase">{{ carousel.description }}</p>
          <h1 class="display-1 fw-bold text-capitalize">{{ carousel.title }}</h1>
          <a href="{% url 'elements:index' %}" class="btn btn-dark">Ver más</a>
        </div>
      </div>
    {% endif %}
    {% if carousel.image3 %}
      <div class="carousel-item">
        <img src="{{ carousel.image3.url }}" class="d-block w-100" alt="slider" style="height:95vh; object-fit:cover;">
        <div class="carousel-caption top-0 mt-4 d-flex flex-column justify-content-center align-items-center">
          <p class="mt-5 fs-3 text-uppercase">{{ carousel.description }}</p>
          <h1 class="display-1 fw-bold text-capitalize">{{ carousel.title }}</h1>
          <a href="{% url 'elements:index' %}" class="btn btn-dark">Ver más</a>
        </div>
      </div>
    {% endif %}
    {% endfor %}





  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
{% endblock %}

EASY/elements/templates/partials/pagination.html
<nav aria-label="Page navigation example">
 <ul class="pagination justify-content-center mt-3">

       {% if page_obj.has_previous %}
           <li class="page-item">
               <a class="page-link" href="?page={{ page_obj.previous_page_number }}">prev</a>
           </li>
       {% endif %}

       {% for i in page_obj.paginator.page_range %}

           {% if i == page_obj.number %}
               <li class="page-item active">
                   <a class="page-link" href="#">{{ i }}</a>
               </li>
           {% else %}
               <li class="page-item">
                   <a class="page-link" href="?page={{ i }}">{{ i }}</a>
               </li>
           {% endif %}

       {% endfor %}

       {% if page_obj.has_next %}
           <li class="page-item">
               <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
           </li>
       {% endif %}
 </ul>
</nav>